name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}  # allow manual runs

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build & Test (${{ matrix.os }} | py${{ matrix.python-version }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Build
        shell: bash
        run: bash build.sh

      - name: Test
        shell: bash
        env:
          PYTHONPATH: ./src
        run: bash test.sh

  package:
    name: Package app (${{ matrix.os }})
    needs: build-and-test
    if: ${{ github.event_name == 'workflow_dispatch' }}  # only when manually triggered
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build with packaging
        shell: bash
        env:
          PACKAGE: "1"
        run: bash build.sh

      - name: Upload packaged artifact
        uses: actions/upload-artifact@v4
        with:
          name: SoleSolutions-${{ runner.os }}
          path: dist/**
